/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ReadAndWrite */

#ifndef _Included_adInterfaceReader_ADInterface
#define _Included_adInterfaceWriter_ADInterface
/* types of error reporting */
#define PRINTALL         3
#define DONTSTOP         0

/* Selectable A/D Ranges codes */
#define BIP60VOLTS       20              /* -60 to 60 Volts */
#define BIP20VOLTS       15              /* -20 to +20 Volts */
#define BIP15VOLTS       21              /* -15 to +15 Volts */
#define BIP10VOLTS       1              /* -10 to +10 Volts */
#define BIP5VOLTS        0              /* -5 to +5 Volts */
#define BIP4VOLTS        16             /* -4 to + 4 Volts */
#define BIP2PT5VOLTS     2              /* -2.5 to +2.5 Volts */
#define BIP2VOLTS        14             /* -2.0 to +2.0 Volts */
#define BIP1PT25VOLTS    3              /* -1.25 to +1.25 Volts */
#define BIP1VOLTS        4              /* -1 to +1 Volts */
#define BIPPT625VOLTS    5              /* -.625 to +.625 Volts */
#define BIPPT5VOLTS      6              /* -.5 to +.5 Volts */
#define BIPPT25VOLTS     12              /* -0.25 to +0.25 Volts */
#define BIPPT2VOLTS      13              /* -0.2 to +0.2 Volts */
#define BIPPT1VOLTS      7              /* -.1 to +.1 Volts */
#define BIPPT05VOLTS     8              /* -.05 to +.05 Volts */
#define BIPPT01VOLTS     9              /* -.01 to +.01 Volts */
#define BIPPT005VOLTS    10             /* -.005 to +.005 Volts */
#define BIP1PT67VOLTS    11             /* -1.67 to +1.67 Volts */
#define BIPPT312VOLTS    17				 /* -0.312 to +0.312 Volts */
#define BIPPT156VOLTS    18				 /* -0.156 to +0.156 Volts */
#define BIPPT125VOLTS    22				 /* -0.125 to +0.125 Volts */
#define BIPPT078VOLTS    19				 /* -0.078 to +0.078 Volts */


#define UNI10VOLTS       100            /* 0 to 10 Volts*/
#define UNI5VOLTS        101            /* 0 to 5 Volts */
#define UNI4VOLTS        114            /* 0 to 4 Volts */
#define UNI2PT5VOLTS     102            /* 0 to 2.5 Volts */
#define UNI2VOLTS        103            /* 0 to 2 Volts */
#define UNI1PT67VOLTS    109            /* 0 to 1.67 Volts */
#define UNI1PT25VOLTS    104            /* 0 to 1.25 Volts */
#define UNI1VOLTS        105            /* 0 to 1 Volt */
#define UNIPT5VOLTS      110            /* 0 to .5 Volt */
#define UNIPT25VOLTS     111            /* 0 to 0.25 Volt */
#define UNIPT2VOLTS      112            /* 0 to .2 Volt */
#define UNIPT1VOLTS      106            /* 0 to .1 Volt */
#define UNIPT05VOLTS     113            /* 0 to .05 Volt */
#define UNIPT02VOLTS     108            /* 0 to .02 Volt*/
#define UNIPT01VOLTS     107            /* 0 to .01 Volt*/

#define MA4TO20          200            /* 4 to 20 ma */
#define MA2TO10          201            /* 2 to 10 ma */
#define MA1TO5           202            /* 1 to 5 ma */
#define MAPT5TO2PT5      203            /* .5 to 2.5 ma */
#define MA0TO20          204            /* 0 to 20 ma */
#define BIPPT025AMPS     205            /* -0.025 to 0.025 ma */

#define UNIPOLAR		 300
#define BIPOLAR			 301
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     ReadChannel
	* Method:    cbVIn
	* Signature: (IIIFI)I
	*/
	JNIEXPORT jfloat JNICALL Java_adInterfaceReader_ADInterface_cbVIn
		(JNIEnv *, jobject, jint, jint, jint, jfloat, jint);

	JNIEXPORT jfloat JNICALL Java_adInterfaceWriter_ADInterface_cbVOut
		(JNIEnv *, jobject, jint, jint, jint, jfloat, jint);

#ifdef __cplusplus
}
#endif
#endif