Building Controls Virtual Test Bed: cclient.c File Reference
cclient.c File Reference
Simple simulation program to illustrate implementation of a client.
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "utilSocket.h"
Functions
int main (int argc, char *argv[])
Main function.
Detailed Description
Simple simulation program to illustrate implementation of a client.
Author
Michael Wetter, Simulation Research Group, LBNL, MWett.nosp@m.er@l.nosp@m.bl.go.nosp@m.v
Date
2012-07-19
This file is a simple simulation program written in C to illustrate how to implement a client. The program simulates two rooms, each represented by a first order ordinary differential equation that describes the time rate of change of the room temperature. Input to the room model is the control signal for a heater. The control signal is obtained from Ptolemy II. Output of the model is the room temperature, which is sent to Ptolemy II. The differential equation is solved using an explicit Euler integration.
Definition in file cclient.c.
Function Documentation
int main (int argc, char * argv[])
Main function.
Definition at line 36 of file cclient.c.
References closeipc(), dblValRea, establishclientsocket(), exchangedoubleswithsocket(), flaRea, fprintf(), i, nDblWri, retVal, sendclientmessage(), simTimRea, and sockfd.