Building Controls Virtual Test Bed: DTDValidator.MyErrorHandler Class Reference
DTDValidator.MyErrorHandler Class Reference
Inner class for error handling.
Public Member Functions
void warning (SAXParseException e) throws SAXException
Writes warning messages to System.err
void error (SAXParseException e) throws SAXException
Writes error messages to System.err
void fatalError (SAXParseException e) throws SAXException
Writes error messages to System.err
Private Member Functions
void printInfo (String s, SAXParseException e)
Prints the error message to System.err
Detailed Description
Inner class for error handling.
Definition at line 52 of file DTDValidator.java.
Member Function Documentation
void DTDValidator.MyErrorHandler.error (SAXParseException e) throws SAXException inline
Writes error messages to System.err
Parameters
e The exception
Exceptions
SAXException If a SAXException occurs
Definition at line 69 of file DTDValidator.java.
References DTDValidator.MyErrorHandler.printInfo().
Referenced by DTDValidator.MyErrorHandler.fatalError().
void DTDValidator.MyErrorHandler.fatalError (SAXParseException e) throws SAXException inline
Writes error messages to System.err
Parameters
e The exception
Exceptions
SAXException If a SAXException occurs
Definition at line 79 of file DTDValidator.java.
References DTDValidator.MyErrorHandler.error().
void DTDValidator.MyErrorHandler.printInfo (String s, SAXParseException e) inline private
Prints the error message to System.err
Parameters
s The string that will be added in front of the exception message
e The exception
Definition at line 89 of file DTDValidator.java.
Referenced by DTDValidator.MyErrorHandler.error(), and DTDValidator.MyErrorHandler.warning().
void DTDValidator.MyErrorHandler.warning (SAXParseException e) throws SAXException inline
Writes warning messages to System.err
Parameters
e The exception
Exceptions
SAXException If a SAXException occurs
Definition at line 59 of file DTDValidator.java.
References DTDValidator.MyErrorHandler.printInfo().
The documentation for this class was generated from the following file:
DTDValidator.java