Building Controls Virtual Test Bed: bacnet.util.BACnetDeviceManager Class Reference
bacnet.util.BACnetDeviceManager Class Reference
This is the driver class in BACnet.
Classes
enum BacnetApplicationTag
enumeration object, contains all the BACnet application tags specified in BACnet Standard used in writing property to BACnet device
enum BacObjectType
Enumeration object, contains all the object names specified in BACnet Standard, including BACnet Device Object and non-Device BACnet objects.
enum BacProperty
BACnet property enumeration object, contains major properties specified in BACnet Standard, including BACnet Device propety and non Device BACnet Object property.
Public Member Functions
String getReadPropertyBinaryPath ()
Returns the bacrp binary file path.
String getWritePropertyBinaryPath ()
Returns the bacwp binary file path.
String getGlobalwiBinaryPath ()
Returns the globalwi binary file path.
ArrayList< Integer > findDevice () throws IllegalActionException
Find BACnet devices in the network and return an integer list with their instance number.
ArrayList< BACnetObjectType > parseBACnetObjectType (final String s) throws ParserConfigurationException, SAXException, IOException
Parse the configuration file and generate an ArrayList that contains the xml content as specified in the configuration file, it is called in readXMLConfigurationFile (see bacnet.util.BACnet).
ArrayList< Integer > readDeviceArray (final ArrayList< BACnetObjectType > bot_arr) throws NumberFormatException
Read device instance from parsed ArrayList.
ArrayList< BACnetObject > readObjectList (final ArrayList< BACnetObjectType > bot_arr, final int dev_inst) throws NumberFormatException
Read a subset of all objects associated with a device from ArrayList.
ArrayList< BACnetCompleteProperty > readDevicePropertyList (final ArrayList< BACnetObjectType > bot_arr, final int dev_inst) throws NumberFormatException
Get an arraylist with elements of BACnetCompleteProerty, one for each property of BACnet device and BACnet objects.
ArrayList< BACnetCompleteProperty > readCompleteObjectPropertyList (final ArrayList< BACnetObjectType > bot_arr, final int dev_inst, final String obj_type, final int obj_inst)
Read complete object property list from BACnetObjectype.
ArrayList< ProcessBuilder > getProcesses (ArrayList< BACnetCompleteProperty > prop_arr)
Prepare the process to be executed.
void validateApplicationTag (final String s) throws IllegalArgumentException
Application tag validaton.
void validatePropertyName (final String s) throws IllegalArgumentException
Property name validation.
void validateObjectType (final String s) throws IllegalArgumentException
object type validation.
void validateXMLFile (final String xmlfile, final Schema schema) throws SAXException, FileNotFoundException,IOException
XMLfile validation.
Schema loadSchema (final String name) throws SAXException
Load schema.
Static Protected Member Functions
static String toString (String arg) throws IllegalArgumentException
Gets a string representation of the enumeration.
Static Private Attributes
static final String bcvtbhome = System.getenv("BCVTB_HOME")
String that points to root directory of the BCVTB.
static final String LS = System.getProperty("line.separator")
System-dependent line separator.
static final String FS = System.getProperty("file.separator")
System-dependent file separator.
static final String osName = System.getProperty("os.name")
Name of the operating system.
Detailed Description
This is the driver class in BACnet.
It is used mainly by BACnet.java. It is used to process BACnetObjectType read from configuration file, and to translate them to processes, to be executed by BACnet-stack command.
This class is called by BACnet(seebacnet.util.BACnet) to get reading and writing processes, BACnetReader(see bacnet.actor.BACnetReader) to get processes to read property from BACnet device, and by BACnetWrtier (see bacnet.actor.BACnetWriter) to to get processes to write property to BACnet device.
Author
Zhengwei Li
Version
1.0
Since
bcvtb 0.5.0
Definition at line 123 of file BACnetDeviceManager.java.
Member Function Documentation
ArrayList<Integer> bacnet.util.BACnetDeviceManager.findDevice () throws IllegalActionException inline
Find BACnet devices in the network and return an integer list with their instance number.
It is called in checkConnection() (see bacnet.util.BACnet).
Returns
interger arraylist with the elements of device instance number of those devices found in the network
Exceptions
IllegalActionException if an error occurs.
Definition at line 462 of file BACnetDeviceManager.java.
References bacnet.util.BACnetDeviceManager.getGlobalwiBinaryPath(), and bacnet.util.BACnetDeviceManager.LS.
String bacnet.util.BACnetDeviceManager.getGlobalwiBinaryPath () inline
Returns the globalwi binary file path.
It is called in findDevice, (see bacnet.util.BACnetDeviceManager).
Returns
file path of globalwi binary
Definition at line 442 of file BACnetDeviceManager.java.
References bacnet.util.BACnetDeviceManager.bcvtbhome, bacnet.util.BACnetDeviceManager.FS, and bacnet.util.BACnetDeviceManager.osName.
Referenced by bacnet.util.BACnetDeviceManager.findDevice().
ArrayList<ProcessBuilder> bacnet.util.BACnetDeviceManager.getProcesses (ArrayList< BACnetCompleteProperty > prop_arr) inline
Prepare the process to be executed.
Parameters
prop_arr arraylist with elements of BACnetCompleteProperty
Returns
arraylist with elements of ProcessBuilder for writing property to device
Definition at line 796 of file BACnetDeviceManager.java.
References bacnet.util.BACnetDeviceManager.getReadPropertyBinaryPath(), bacnet.util.BACnetDeviceManager.getWritePropertyBinaryPath(), and i.
String bacnet.util.BACnetDeviceManager.getReadPropertyBinaryPath () inline
Returns the bacrp binary file path.
This function is called in prepareProcesses, (see bacnet.util.BACnetDeviceManager)
Returns
file path of read property binary in BACnet-stack
Definition at line 403 of file BACnetDeviceManager.java.
References bacnet.util.BACnetDeviceManager.bcvtbhome, bacnet.util.BACnetDeviceManager.FS, and bacnet.util.BACnetDeviceManager.osName.
Referenced by bacnet.util.BACnetDeviceManager.getProcesses().
String bacnet.util.BACnetDeviceManager.getWritePropertyBinaryPath () inline
Returns the bacwp binary file path.
This function is called in prepareProcesses, (see bacnet.util.BACnetDeviceManager).
Returns
file path of write property in BACnet-stack
Definition at line 423 of file BACnetDeviceManager.java.
References bacnet.util.BACnetDeviceManager.bcvtbhome, bacnet.util.BACnetDeviceManager.FS, and bacnet.util.BACnetDeviceManager.osName.
Referenced by bacnet.util.BACnetDeviceManager.getProcesses().
Schema bacnet.util.BACnetDeviceManager.loadSchema (final String name) throws SAXException inline
Load schema.
It is called in validateSyntax(), (see bacnet.actor.BACnetReader and bacnet.actor.BACnetWriter).
Parameters
name file name of the schema file
Returns
schema the Schema object
Exceptions
SAXException if error occurs in schema loading process
Definition at line 1009 of file BACnetDeviceManager.java.
References bacnet.util.BACnetDeviceManager.LS.
ArrayList<BACnetObjectType> bacnet.util.BACnetDeviceManager.parseBACnetObjectType (final String s) throws ParserConfigurationException, SAXException, IOException inline
Parse the configuration file and generate an ArrayList that contains the xml content as specified in the configuration file, it is called in readXMLConfigurationFile (see bacnet.util.BACnet).
Parameters
s path of configuration file
Returns
ArrayList containing BACnetObjectTypes
Exceptions
ParserConfigurationException if errors occur in configuring parser
SAXException if errors occur in parsing configuration file
IOException if I/O exception occurs in parsing configuration file
Definition at line 546 of file BACnetDeviceManager.java.
References bacnet.util.BACnetDeviceManager.LS.
ArrayList<BACnetCompleteProperty> bacnet.util.BACnetDeviceManager.readCompleteObjectPropertyList (final ArrayList< BACnetObjectType > bot_arr, final int dev_inst, final String obj_type, final int obj_inst) inline
Read complete object property list from BACnetObjectype.
It is called in readDevicePropertyList, (see bacnet.util.BACnetDeviceManager).
Parameters
bot_arr BACnetObjecttype cotaining xml content
dev_inst device instance number
obj_type object name
obj_inst object instance
Returns
property_array arraylist with elements of BACnetCompleteProperty
Definition at line 755 of file BACnetDeviceManager.java.
References bacnet.util.BACnetObjectType.getBOTInst(), bacnet.util.BACnetObjectType.getBOTName(), and i.
Referenced by bacnet.util.BACnetDeviceManager.readDevicePropertyList().
ArrayList<Integer> bacnet.util.BACnetDeviceManager.readDeviceArray (final ArrayList< BACnetObjectType > bot_arr) throws NumberFormatException inline
Read device instance from parsed ArrayList.
It is called in readDeviceArray, (see bacnet.util.BACnet).
Parameters
bot_arr ArrayList containing xml configuration file content
Returns
ArrayList with elements of device instance number
Exceptions
NumberFormatException if error occurs while converting instance number from string to integer
Definition at line 584 of file BACnetDeviceManager.java.
References bacnet.util.BACnetObjectType.getBOTName(), i, and bacnet.util.BACnetDeviceManager.LS.
ArrayList<BACnetCompleteProperty> bacnet.util.BACnetDeviceManager.readDevicePropertyList (final ArrayList< BACnetObjectType > bot_arr, final int dev_inst) throws NumberFormatException inline
Get an arraylist with elements of BACnetCompleteProerty, one for each property of BACnet device and BACnet objects.
It is called in readDevicePropertyArray, (see bacnet.util.BACnet).
Parameters
bot_arr ArrayList containing configuration file content
dev_inst device instance number
Returns
arraylist with elements of BACnetCompleteProperty
Exceptions
NumberFormatException if object/device instance number is not integer
Definition at line 685 of file BACnetDeviceManager.java.
References bacnet.util.BACnetObjectType.getBOTInst(), bacnet.util.BACnetObjectType.getBOTName(), bacnet.util.BACnetObject.getObjectType(), i, bacnet.util.BACnetDeviceManager.LS, bacnet.util.BACnetDeviceManager.readCompleteObjectPropertyList(), and bacnet.util.BACnetDeviceManager.readObjectList().
ArrayList<BACnetObject> bacnet.util.BACnetDeviceManager.readObjectList (final ArrayList< BACnetObjectType > bot_arr, final int dev_inst) throws NumberFormatException inline
Read a subset of all objects associated with a device from ArrayList.
It is called in readDevicePropertyList, (see bacnet.util.BACnetDeviceManager).
Parameters
bot_arr ArrayList containing XML configuration file
dev_inst device instance number
Returns
object_array ArrayList with elements of BACnetObject
Exceptions
NumberFormatException if error occurs while trying to convert object instance number from string to integer
Definition at line 621 of file BACnetDeviceManager.java.
References bacnet.util.BACnetObjectType.getBOTInst(), bacnet.util.BACnetObjectType.getBOTName(), i, bacnet.util.BACnetDeviceManager.LS, and bacnet.util.BACnetDeviceManager.toString().
Referenced by bacnet.util.BACnetDeviceManager.readDevicePropertyList().
static String bacnet.util.BACnetDeviceManager.toString (String arg) throws IllegalArgumentException inline static protected
Gets a string representation of the enumeration.
Parameters
arg enumeration to be converted to string
Returns
the string representation of the enumeration
Exceptions
IllegalArgumentException if the argument is not BacnetApplicationTag, BacProperty or BacObjectType
Definition at line 848 of file BACnetDeviceManager.java.
References i, bacnet.util.BACnetDeviceManager.LS, r, and strLen.
Referenced by bacnet.util.BACnetDeviceManager.readObjectList(), bacnet.util.BACnetDeviceManager.validateApplicationTag(), bacnet.util.BACnetDeviceManager.validateObjectType(), and bacnet.util.BACnetDeviceManager.validatePropertyName().
void bacnet.util.BACnetDeviceManager.validateApplicationTag (final String s) throws IllegalArgumentException inline
Application tag validaton.
It is called in validateAttributes(), (see bacnet.util.BACnet).
Parameters
s string read from configuration file
Exceptions
IllegalArgumentException if s is not part of BacnetApplicationTag enum type
Definition at line 906 of file BACnetDeviceManager.java.
References bacnet.util.BACnetDeviceManager.LS, and bacnet.util.BACnetDeviceManager.toString().
void bacnet.util.BACnetDeviceManager.validateObjectType (final String s) throws IllegalArgumentException inline
object type validation.
It is called in validateObjectType(), (see bacnet.util.BACnet).
Parameters
s string read from xml configration file
Exceptions
IllegalArgumentException if s is not part of the BacProperty enum type
Definition at line 949 of file BACnetDeviceManager.java.
References bacnet.util.BACnetDeviceManager.LS, and bacnet.util.BACnetDeviceManager.toString().
void bacnet.util.BACnetDeviceManager.validatePropertyName (final String s) throws IllegalArgumentException inline
Property name validation.
It is called in validatePropertyName(), (see bacnet.util.BACnet).
Parameters
s string read from xml configration file
Exceptions
IllegalArgumentException if s is not part of the BacProperty enum type
Definition at line 928 of file BACnetDeviceManager.java.
References bacnet.util.BACnetDeviceManager.LS, and bacnet.util.BACnetDeviceManager.toString().
void bacnet.util.BACnetDeviceManager.validateXMLFile (final String xmlfile, final Schema schema) throws SAXException, FileNotFoundException,IOException inline
XMLfile validation.
It is called in validateSyntax(), (see bacnet.actor.BACnetReader and bacnet.actor.BACnetWriter).
Parameters
xmlfile file name of the xmlfile
schema schema used to validate the xmlfile
Exceptions
FileNotFoundException if either xmlfile or schema couldn't be found
SAXException if xmlfile is not properly written
IOException if error occurs when reading xmlfile or schema
Definition at line 974 of file BACnetDeviceManager.java.
References bacnet.util.BACnetDeviceManager.LS, and source.
Member Data Documentation
final String bacnet.util.BACnetDeviceManager.bcvtbhome = System.getenv("BCVTB_HOME") static private
String that points to root directory of the BCVTB.
Definition at line 127 of file BACnetDeviceManager.java.
Referenced by bacnet.util.BACnetDeviceManager.getGlobalwiBinaryPath(), bacnet.util.BACnetDeviceManager.getReadPropertyBinaryPath(), and bacnet.util.BACnetDeviceManager.getWritePropertyBinaryPath().
final String bacnet.util.BACnetDeviceManager.FS = System.getProperty("file.separator") static private
System-dependent file separator.
Definition at line 133 of file BACnetDeviceManager.java.
Referenced by bacnet.util.BACnetDeviceManager.getGlobalwiBinaryPath(), bacnet.util.BACnetDeviceManager.getReadPropertyBinaryPath(), and bacnet.util.BACnetDeviceManager.getWritePropertyBinaryPath().
final String bacnet.util.BACnetDeviceManager.LS = System.getProperty("line.separator") static private
System-dependent line separator.
Definition at line 130 of file BACnetDeviceManager.java.
Referenced by bacnet.util.BACnetDeviceManager.findDevice(), bacnet.util.BACnetDeviceManager.loadSchema(), bacnet.util.BACnetDeviceManager.parseBACnetObjectType(), bacnet.util.BACnetDeviceManager.readDeviceArray(), bacnet.util.BACnetDeviceManager.readDevicePropertyList(), bacnet.util.BACnetDeviceManager.readObjectList(), bacnet.util.BACnetDeviceManager.toString(), bacnet.util.BACnetDeviceManager.validateApplicationTag(), bacnet.util.BACnetDeviceManager.validateObjectType(), bacnet.util.BACnetDeviceManager.validatePropertyName(), and bacnet.util.BACnetDeviceManager.validateXMLFile().
final String bacnet.util.BACnetDeviceManager.osName = System.getProperty("os.name") static private
Name of the operating system.
Definition at line 136 of file BACnetDeviceManager.java.
Referenced by bacnet.util.BACnetDeviceManager.getGlobalwiBinaryPath(), bacnet.util.BACnetDeviceManager.getReadPropertyBinaryPath(), and bacnet.util.BACnetDeviceManager.getWritePropertyBinaryPath().
The documentation for this class was generated from the following file:
BACnetDeviceManager.java