Building Controls Virtual Test Bed: bacnet.util.BACnetObjectType Class Reference
bacnet.util.BACnetObjectType Class Reference
This class reads the XML configuration file and stores the data in the BACnetObjectType data type.
Public Member Functions
BACnetObjectType (final String name, final String instance, final ArrayList< BACnetPropertyValue > mapPI, final HashMap mapOTname, final HashMap mapOTinst, final HashMap piOrder, final HashMap otOrder)
Construct an instance of BACnet object.
BACnetObjectType ()
Empty constructor.
String getBOTName ()
Get the bacnet object type name.
String getBOTInst ()
Get the instance of the bacnet object type.
ArrayList< BACnetPropertyValue > getBOTPI ()
Get the map of the property identifier.
HashMap getBACnetObjectTypeNameMap ()
Get the map of the object type.
HashMap getBACnetObjectTypeInstanceMap ()
Get the map of the object type.
HashMap getBACnetObjectTypePropertyIdentifierOrder ()
Get the map of the property identifier index.
HashMap getBACnetObjectTypeOrder ()
Get the map of the bacnet object type index.
ArrayList< BACnetObjectType > parseObjectType (final String s) throws ParserConfigurationException, SAXException, IOException
Read bacnet object types from the xml configuration.
ArrayList< String > readDeviceInst (final String s) throws FileNotFoundException, ParserConfigurationException, SAXException, IOException
Read ArrayList String from xml configuration file.
BACnetObjectType readBacnetDeviceObjectType (final String dev_inst, final String s) throws FileNotFoundException, ParserConfigurationException, SAXException, IOException
Read Bancet DeviceObjectType from xml configuration file.
BACnetObjectType readBacnetNonDeviceObjectType (final String dev_inst, final String obj_inst, final String obj_name, final String s) throws FileNotFoundException, ParserConfigurationException, SAXException, IOException
Read NonDevice BACnetObjectType from xml configuration file.
String convertObjectName (String orStr)
Convert object name to the same convention as in BacnetDeviceManager.
Protected Attributes
String bot_name
The BACnetObjectType name.
String bot_instance
The BACnetObjectType instance.
ArrayList< BACnetPropertyValue > bot_mapPI
ArrayList with elements of BACnetPropertyValue.
HashMap bot_mapOTname
Hashmap containing the index and name of the objecty type pair.
HashMap bot_mapOTinst
Hashmap containing the index and object instance number pair for BACnet Device Object and device instance number and object instance number pair for BACnet non-Device Object.
HashMap bot_piOrder
Hashmap containing the name and index pair of property identifier.
HashMap bot_otOrder
Hashmap containing the instance and index pair of object type.
Static Private Attributes
static final String LS = System.getProperty("line.separator")
System-dependent line separator.
Detailed Description
This class reads the XML configuration file and stores the data in the BACnetObjectType data type.
Author
Zhengwei Li
Definition at line 98 of file BACnetObjectType.java.
Constructor & Destructor Documentation
bacnet.util.BACnetObjectType.BACnetObjectType (final String name, final String instance, final ArrayList< BACnetPropertyValue > mapPI, final HashMap mapOTname, final HashMap mapOTinst, final HashMap piOrder, final HashMap otOrder) inline
Construct an instance of BACnet object.
Parameters
name name of the object type
instance instance number of the object type
mapPI ArrayList containing the elements of BACnetPropertyValue(name and value pair)
mapOTname Hashmap containing the index and name of the objecty type pair
mapOTinst Hashmap containing the index and object instance number pair for BACnet Device Object and device instance number and object instance number pair for BACnet nonDevice Object
piOrder Hashmap containing the name and index pair of property identifier
otOrder Hashmap containing the instance and index pair of object type
Definition at line 113 of file BACnetObjectType.java.
References bacnet.util.BACnetObjectType.bot_instance, bacnet.util.BACnetObjectType.bot_mapOTinst, bacnet.util.BACnetObjectType.bot_mapOTname, bacnet.util.BACnetObjectType.bot_mapPI, bacnet.util.BACnetObjectType.bot_name, bacnet.util.BACnetObjectType.bot_otOrder, and bacnet.util.BACnetObjectType.bot_piOrder.
bacnet.util.BACnetObjectType.BACnetObjectType () inline
Empty constructor.
Definition at line 134 of file BACnetObjectType.java.
Referenced by bacnet.util.BACnetObjectType.readBacnetDeviceObjectType(), and bacnet.util.BACnetObjectType.readBacnetNonDeviceObjectType().
Member Function Documentation
String bacnet.util.BACnetObjectType.convertObjectName (String orStr) inline
Convert object name to the same convention as in BacnetDeviceManager.
Parameters
orStr object name in xml configuration file
Returns
object name to be used in BACnetDeviceManager
Definition at line 532 of file BACnetObjectType.java.
Referenced by bacnet.util.BACnetObjectType.readBacnetDeviceObjectType(), and bacnet.util.BACnetObjectType.readBacnetNonDeviceObjectType().
HashMap bacnet.util.BACnetObjectType.getBACnetObjectTypeInstanceMap () inline
Get the map of the object type.
Returns
the map containing object type
Definition at line 176 of file BACnetObjectType.java.
References bacnet.util.BACnetObjectType.bot_mapOTinst.
HashMap bacnet.util.BACnetObjectType.getBACnetObjectTypeNameMap () inline
Get the map of the object type.
Returns
the map containing object type
Definition at line 167 of file BACnetObjectType.java.
References bacnet.util.BACnetObjectType.bot_mapOTname.
HashMap bacnet.util.BACnetObjectType.getBACnetObjectTypeOrder () inline
Get the map of the bacnet object type index.
Returns
the map containing object type name and index
Definition at line 192 of file BACnetObjectType.java.
References bacnet.util.BACnetObjectType.bot_otOrder.
HashMap bacnet.util.BACnetObjectType.getBACnetObjectTypePropertyIdentifierOrder () inline
Get the map of the property identifier index.
Returns
the map contating property identifier name and index
Definition at line 184 of file BACnetObjectType.java.
References bacnet.util.BACnetObjectType.bot_piOrder.
String bacnet.util.BACnetObjectType.getBOTInst () inline
Get the instance of the bacnet object type.
Returns
the instance of the bacnet object type
Definition at line 149 of file BACnetObjectType.java.
References bacnet.util.BACnetObjectType.bot_instance.
Referenced by bacnet.util.BACnetDeviceManager.readCompleteObjectPropertyList(), bacnet.util.BACnetDeviceManager.readDevicePropertyList(), and bacnet.util.BACnetDeviceManager.readObjectList().
String bacnet.util.BACnetObjectType.getBOTName () inline
Get the bacnet object type name.
Returns
the name of the bacnet object type
Definition at line 141 of file BACnetObjectType.java.
References bacnet.util.BACnetObjectType.bot_name.
Referenced by bacnet.util.BACnetDeviceManager.readCompleteObjectPropertyList(), bacnet.util.BACnetDeviceManager.readDeviceArray(), bacnet.util.BACnetDeviceManager.readDevicePropertyList(), and bacnet.util.BACnetDeviceManager.readObjectList().
ArrayList<BACnetPropertyValue> bacnet.util.BACnetObjectType.getBOTPI () inline
Get the map of the property identifier.
Returns
the map containing property identifier
Definition at line 158 of file BACnetObjectType.java.
References bacnet.util.BACnetObjectType.bot_mapPI.
ArrayList<BACnetObjectType> bacnet.util.BACnetObjectType.parseObjectType (final String s) throws ParserConfigurationException, SAXException, IOException inline
Read bacnet object types from the xml configuration.
Parameters
s name of configuration file
Returns
ArrayList with elements of bacnet object type
Exceptions
FileNotFoundException if configuration file couldn't be found
ParserConfigurationException if configuration file couldn't be read properly
SAXException if error occurs while configuration file is parsed
IOException if I/O error occurs while parsing configuration file
Definition at line 206 of file BACnetObjectType.java.
References i, bacnet.util.BACnetObjectType.LS, bacnet.util.BACnetObjectType.readBacnetDeviceObjectType(), bacnet.util.BACnetObjectType.readBacnetNonDeviceObjectType(), and bacnet.util.BACnetObjectType.readDeviceInst().
BACnetObjectType bacnet.util.BACnetObjectType.readBacnetDeviceObjectType (final String dev_inst, final String s) throws FileNotFoundException, ParserConfigurationException, SAXException, IOException inline
Read Bancet DeviceObjectType from xml configuration file.
Parameters
s xml configuration file path
dev_inst device instance
Returns
Bacnet Device Object Type
Exceptions
FileNotFoundException if configuration file can't be found
ParserConfigurationException if configuration file couldn't be read properly
SAXException if error occurs while configuration file is parsed
IOException if I/O error occurs while parsing configuration file
Definition at line 308 of file BACnetObjectType.java.
References bacnet.util.BACnetObjectType.BACnetObjectType(), and bacnet.util.BACnetObjectType.convertObjectName().
Referenced by bacnet.util.BACnetObjectType.parseObjectType().
BACnetObjectType bacnet.util.BACnetObjectType.readBacnetNonDeviceObjectType (final String dev_inst, final String obj_inst, final String obj_name, final String s) throws FileNotFoundException, ParserConfigurationException, SAXException, IOException inline
Read NonDevice BACnetObjectType from xml configuration file.
Parameters
dev_inst device instance number
obj_inst object instance number
Returns
a non device BACnetObjectType
Exceptions
FileNotFoundException if configuration file can't be found
ParserConfigurationException if configuration file couldn't be read properly
SAXException if error occurs while configuration file is parsed
IOException if I/O error occurs while parsing configuration file
Definition at line 418 of file BACnetObjectType.java.
References bacnet.util.BACnetObjectType.BACnetObjectType(), and bacnet.util.BACnetObjectType.convertObjectName().
Referenced by bacnet.util.BACnetObjectType.parseObjectType().
ArrayList<String> bacnet.util.BACnetObjectType.readDeviceInst (final String s) throws FileNotFoundException, ParserConfigurationException, SAXException, IOException inline
Read ArrayList String from xml configuration file.
Parameters
s xml configuation file path
Returns
ArrayList containing elements of Bacnet Device
Exceptions
FileNotFoundException if configuration file can't be found
ParserConfigurationException if configuration file couldn't be read properly
SAXException if error occurs while configuration file is parsed
IOException if I/O error occurs while parsing configuration file
Definition at line 257 of file BACnetObjectType.java.
Referenced by bacnet.util.BACnetObjectType.parseObjectType().
Member Data Documentation
String bacnet.util.BACnetObjectType.bot_instance protected
The BACnetObjectType instance.
Definition at line 541 of file BACnetObjectType.java.
Referenced by bacnet.util.BACnetObjectType.BACnetObjectType(), and bacnet.util.BACnetObjectType.getBOTInst().
HashMap bacnet.util.BACnetObjectType.bot_mapOTinst protected
Hashmap containing the index and object instance number pair for BACnet Device Object and device instance number and object instance number pair for BACnet non-Device Object.
Definition at line 551 of file BACnetObjectType.java.
Referenced by bacnet.util.BACnetObjectType.BACnetObjectType(), and bacnet.util.BACnetObjectType.getBACnetObjectTypeInstanceMap().
HashMap bacnet.util.BACnetObjectType.bot_mapOTname protected
Hashmap containing the index and name of the objecty type pair.
Definition at line 547 of file BACnetObjectType.java.
Referenced by bacnet.util.BACnetObjectType.BACnetObjectType(), and bacnet.util.BACnetObjectType.getBACnetObjectTypeNameMap().
ArrayList<BACnetPropertyValue> bacnet.util.BACnetObjectType.bot_mapPI protected
ArrayList with elements of BACnetPropertyValue.
Definition at line 544 of file BACnetObjectType.java.
Referenced by bacnet.util.BACnetObjectType.BACnetObjectType(), and bacnet.util.BACnetObjectType.getBOTPI().
String bacnet.util.BACnetObjectType.bot_name protected
The BACnetObjectType name.
Definition at line 538 of file BACnetObjectType.java.
Referenced by bacnet.util.BACnetObjectType.BACnetObjectType(), and bacnet.util.BACnetObjectType.getBOTName().
HashMap bacnet.util.BACnetObjectType.bot_otOrder protected
Hashmap containing the instance and index pair of object type.
Definition at line 557 of file BACnetObjectType.java.
Referenced by bacnet.util.BACnetObjectType.BACnetObjectType(), and bacnet.util.BACnetObjectType.getBACnetObjectTypeOrder().
HashMap bacnet.util.BACnetObjectType.bot_piOrder protected
Hashmap containing the name and index pair of property identifier.
Definition at line 554 of file BACnetObjectType.java.
Referenced by bacnet.util.BACnetObjectType.BACnetObjectType(), and bacnet.util.BACnetObjectType.getBACnetObjectTypePropertyIdentifierOrder().
final String bacnet.util.BACnetObjectType.LS = System.getProperty("line.separator") static private
System-dependent line separator.
Definition at line 560 of file BACnetObjectType.java.
Referenced by bacnet.util.BACnetObjectType.parseObjectType().
The documentation for this class was generated from the following file:
BACnetObjectType.java