Building Controls Virtual Test Bed: utilXml.h File Reference
dummy/utilXml.h File Reference
Functions
int getepvariables (char *const fileName, char *const myOutputVarsName, char *const myOutputVarsType, int *const myNumOutputVars, char *const myInputKeys, int *const myNumInputKeys, char *const myInputVars, int *const myNumInputVars, int *const myInputVarsType, int *const myStrLen)
This method will return the input and output variable for EnergyPlus in sequence.
]
Parameters
fileName the xml file name.
exp the xPath expression.
str string to store the found values, semicolon separated.
nVals number of values found.
strLen the string length allocated.
int getxmlvalues (char *const fileName, char *const exp, char *const myVals, int *const myNumVals, int const myStrLen)
int getnumberofxmlvalues (char *const fileName, char *const exp)
int getxmlvaluesf (char *const fileName, char *const exp, char *const atrName, int *const nVal, char *const str, int *const strLen)
int getxmlvalue (char *const fileName, char *const exp, char *const str, int *const nVals, int const strLen)
int check_variable_cfg_Validate (char *const fileName)
This method checks the validity of the variables configuration xml file for a given dtd file that is specified in the variables configuration file.
Function Documentation
int check_variable_cfg_Validate (char *const fileName)
This method checks the validity of the variables configuration xml file for a given dtd file that is specified in the variables configuration file.
Return values: -1 Error in the file 0 File is validate
Definition at line 869 of file util/utilXml.c.
References fprintf().
Referenced by getepvariables(), and getxmlvaluesf().
int getepvariables (char *const fileName, char *const myOutputVarsName, char *const myOutputVarsType, int *const myNumOutputVars, char *const myInputKeys, int *const myNumInputKeys, char *const myInputVars, int *const myNumInputVars, int *const myInputVarsType, int *const myStrLen)
This method will return the input and output variable for EnergyPlus in sequence.
Parameters
fileName the variable configuration file name.
myOutputVarsName Array to store the output variable names found.
myOutputvarsType Array to store the output variable types found.
myNumOutputVars Integer holder to store number of output variables found.
myInputKeys Array to store the input variable keys.
myNumInputKeys Integer holder to store number of input variable keys.
myInputVars Array to store the name of input variables found.
myNumInputVars Integer holder to store number of input variables found.
myInputVarsType Integer array to store the corresponding input variable types in myInputVars.
myStrLen The length of the string that is passed to this function.
Definition at line 241 of file util/utilXml.c.
References Buff, BUFFSIZE, check_variable_cfg_Validate(), EPend(), EPstart(), ERROR_STATUS, fprintf(), freeResource(), i, inputKeys, inputVars, inputVarsType, numInputKeys, numInputVars, numOutputVars, outputVarsName, outputVarsType, source, and strLen.
int getnumberofxmlvalues (char *const fileName, char *const exp)
Definition at line 729 of file util/utilXml.c.
References fprintf(), getxmlvalues(), PARSEVALUE, and strLen.
int getxmlvalue (char *const fileName, char *const exp, char *const str, int *const nVals, int const strLen)
Definition at line 828 of file util/utilXml.c.
References fprintf(), getxmlvalues(), and PARSEVALUE.
Referenced by getsockethost(), and getsocketportnumber().
int getxmlvalues (char *const fileName, char *const exp, char *const myVals, int *const myNumVals, int const myStrLen)
Definition at line 549 of file util/utilXml.c.
References att, Buff, BUFFSIZE, Stack::cur, end(), expStk, fprintf(), Stack::head, i, numVals, PARSEVALUE, stackPopBCVTB(), stackPushBCVTB(), start(), strLen, Stack::top, and vals.
Referenced by getnumberofxmlvalues(), getxmlvalue(), and getxmlvaluesf().
int getxmlvaluesf (char *const fileName, char *const exp, char *const atrName, int *const nVal, char *const str, int *const strLen)
This part of the code is for compatibility with the BCVTB version 0.2 and earlier
This part of the code is for compatibility with the BCVTB version 0.2 and earlier
Definition at line 775 of file util/utilXml.c.
References check_variable_cfg_Validate(), fprintf(), getxmlvalues(), and PARSEVALUE.