Building Controls Virtual Test Bed: exchangeDoublesWithSocket.m File Reference
exchangeDoublesWithSocket.m File Reference
Functions
id are:gov: (id lbl,[gov] id NDBLMAX)
Ensure that we will not
attempt to read too many
double values if (nDblRea > NDBLMAX) msg
throw (ME)
Ensure that we read as many
double values as expected if (nDblReceived~=nDblRea) msg
Variables
function [retVal, flaRea, simTimRea, dblValRea]
exchanges data with the BCVTB
The input arguments are
ME
retVal = -1
end Get pointer of arguments INT32PTR ='int32Ptr'
DBLPTR ='doublePtr'
myFlaWri = libpointer(INT32PTR, int32(flaWri))
myFlaRea = libpointer(INT32PTR, int32(0))
nDblWri = libpointer(INT32PTR, length(dblValWri))
mySimTimWri = libpointer(DBLPTR, double(simTimWri))
myDblValWri = libpointer(DBLPTR, double(dblValWri))
mySimTimRea = libpointer(DBLPTR, double(0))
myNDblRea = libpointer(INT32PTR, int32(0))
myDblValRea = libpointer(DBLPTR, double(zeros(1, nDblRea)))
VAL ='Value'
nDblReceived = get(myNDblRea, VAL)
end Get return values from pointers flaRea = get(myFlaRea, VAL)
simTimRea = get(mySimTimRea, VAL)
dblValRea = get(myDblValRea, VAL)
Function Documentation
id are:gov: (id lbl, [gov] id NDBLMAX) virtual
Ensure that we will not attempt to read too many double values if (nDblRea , NDBLMAX)
Ensure that we read as many double values as expected if (nDblReceived~ = nDblRea)
throw (ME)
Variable Documentation
exchanges data with the BCVTB The input arguments are
Definition at line 12 of file exchangeDoublesWithSocket.m.
DBLPTR ='doublePtr'
Definition at line 52 of file exchangeDoublesWithSocket.m.
dblValRea = get(myDblValRea, VAL)
Definition at line 90 of file exchangeDoublesWithSocket.m.
Referenced by main().
end Get return values from pointers flaRea = get(myFlaRea, VAL)
Definition at line 88 of file exchangeDoublesWithSocket.m.
Referenced by main().
function[retVal, flaRea, simTimRea, dblValRea]
Initial value:
= ...
    exchangeDoublesWithSocket(sockfd, flaWri, nDblRea, simTimWri, dblValWri)
% EXCHANGEDOUBLESWITHSOCKET - Exchanges data with the BCVTB
%
%  [retVal, flaRea, simTimRea, dblValRea] = exchangeDoublesWithSocket(...
%                            sockfd, flaWri, nDblRea, simTimWri, dblValWri)
Definition at line 1 of file exchangeDoublesWithSocket.m.
end Get pointer of arguments INT32PTR ='int32Ptr'
Definition at line 51 of file exchangeDoublesWithSocket.m.
ME
Initial value:
= MException('BCVTB:ConfigurationError', ...
                    msg)
Definition at line 44 of file exchangeDoublesWithSocket.m.
myDblValRea = libpointer(DBLPTR, double(zeros(1, nDblRea)))
Definition at line 63 of file exchangeDoublesWithSocket.m.
myDblValWri = libpointer(DBLPTR, double(dblValWri))
Definition at line 59 of file exchangeDoublesWithSocket.m.
myFlaRea = libpointer(INT32PTR, int32(0))
Definition at line 54 of file exchangeDoublesWithSocket.m.
Referenced by exchangeDoublesWithBSDSocket().
myFlaWri = libpointer(INT32PTR, int32(flaWri))
Definition at line 53 of file exchangeDoublesWithSocket.m.
Referenced by exchangeDoublesWithBSDSocket().
myNDblRea = libpointer(INT32PTR, int32(0))
Definition at line 62 of file exchangeDoublesWithSocket.m.
mySimTimRea = libpointer(DBLPTR, double(0))
Definition at line 61 of file exchangeDoublesWithSocket.m.
mySimTimWri = libpointer(DBLPTR, double(simTimWri))
Definition at line 58 of file exchangeDoublesWithSocket.m.
nDblReceived = get(myNDblRea, VAL)
Definition at line 75 of file exchangeDoublesWithSocket.m.
nDblWri = libpointer(INT32PTR, length(dblValWri))
Definition at line 56 of file exchangeDoublesWithSocket.m.
Referenced by exchangeDoublesWithBSDSocket(), and main().
retVal = -1
Definition at line 47 of file exchangeDoublesWithSocket.m.
simTimRea = get(mySimTimRea, VAL)
Definition at line 89 of file exchangeDoublesWithSocket.m.
Referenced by main().
VAL ='Value'
Definition at line 74 of file exchangeDoublesWithSocket.m.