Building Controls Virtual Test Bed: processError.m File Reference
processError.m File Reference
Functions
id gov: (['***Error: ', getReport(mException)] fprintf)
fprintf ([' ', 'Trying to send client error from MATLAB to the BCVTB.'])
if ~libisloaded (BCVTBLIB) loadlibrary(BCVTBLIB
throw (ME)
Variables
function retVal
function if the BCVTB library
can be loaded and if sockfd is
not a negative number
function if the BCVTB library
can be loaded and if sockfd is
not a negative then this
function sends signal to the
socket If sending a message to
the socket was successful
Load library if it is not
already loaded BCVTBLIB =getBCVTBLibName()
if bcvtb
ME
Function Documentation
fprintf ()
Referenced by check_variable_cfg_Validate(), disassembleBuffer(), EPstart(), establishclientsocket(), exchangeDoublesWithBSDSocket(), exchangewithsocket(), getDoubleCheckError(), getepvariables(), getepvariablesFMU(), getIntCheckError(), getnumberofxmlvalues(), getrequiredbufferlength(), getsocketportnumber(), getxmlvalue(), getxmlvalues(), getxmlvaluesf(), main(), readbufferfromsocket(), readfromsocket(), save_append(), sendclientmessage(), stackPopBCVTB(), stackPushBCVTB(), start(), and writetosocket().
id gov: (['***Error: ', getReport(mException)] fprintf) virtual
throw (ME)
if ~libisloaded (BCVTBLIB)
Variable Documentation
if bcvtb
Definition at line 28 of file processError.m.
Load library if it is not already loaded BCVTBLIB =getBCVTBLibName()
Definition at line 26 of file processError.m.
ME
Initial value:
= MException('BCVTB:ConnectError', ...
                  msg)
Definition at line 33 of file processError.m.
function if the BCVTB library can be loaded and if sockfd is not a negative number
Definition at line 1 of file processError.m.
else retVal
Initial value:
= processError(mException, sockfd, signal)
% PROCESSERROR - Processes a MATLAB exception
%
%   retVal = processError(mException, sockfd, signal) processes
%   a MATLAB exception.
%   The function writes an error message to the console.
%   Next
Definition at line 1 of file processError.m.
function if the BCVTB library can be loaded and if sockfd is not a negative then this function sends signal to the socket If sending a message to the socket was successful
Definition at line 1 of file processError.m.