Building Controls Virtual Test Bed: simulinkSocket.c File Reference
simulinkSocket.c File Reference
Methods for interfacing Simulink using BSD sockets.
#include "simulinkSocket.h"
Functions
int16_T establishBSDSocket (int16_T *flag)
int16_T exchangeDoublesWithBSDSocket (int16_T *sockfd, int16_T *flaWri, int16_T *flaRea, int16_T *nDblWri, double *simTimWri, double dblValWri[], double *simTimRea, double dblValRea[])
int16_T closeBSDSocket (int16_T *sockfd, int16_T *doClose)
Detailed Description
Methods for interfacing Simulink using BSD sockets.
Author
Michael Wetter, Simulation Research Group, LBNL, MWett.nosp@m.er@l.nosp@m.bl.go.nosp@m.v
Date
2007-12-01
This file provides methods that allows Simulink to establish a socket connection. The file compile.m is using this file.
Definition in file simulinkSocket.c.
Function Documentation
int16_T closeBSDSocket (int16_T * sockfd, int16_T * doClose)
Definition at line 65 of file simulinkSocket.c.
References closeipc(), and sockfd.
int16_T establishBSDSocket (int16_T * flag)
Definition at line 23 of file simulinkSocket.c.
References establishclientsocket(), and retVal.
int16_T exchangeDoublesWithBSDSocket (int16_T * sockfd, int16_T * flaWri, int16_T * flaRea, int16_T * nDblWri, double * simTimWri, double dblValWri[], double * simTimRea, double dblValRea[])
Definition at line 33 of file simulinkSocket.c.
References exchangedoubleswithsocket(), fprintf(), myFlaRea, myFlaWri, NDBLMAX, nDblWri, retVal, and sockfd.